In [4]:
import numpy as np




In [5]:
# 从列表创建数组
arr_from_list = np.array([1, 2, 3, 4, 5])


In [7]:
arr_from_list.size

5

In [8]:
print("从列表创建的数组：", arr_from_list)

# 从元组创建数组
arr_from_tuple = np.array((1, 2, 3, 4, 5))
print("从元组创建的数组：", arr_from_tuple)

从列表创建的数组： [1 2 3 4 5]
从元组创建的数组： [1 2 3 4 5]


In [9]:
# 创建全零数组
zeros_array = np.zeros((2, 3))
print("全零数组：\n", zeros_array)

全零数组：
 [[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
zeros_array.shape()

(2, 3)

In [12]:
zeros_array.size

6

https://lekhuyen.medium.com/an-overview-of-vgg16-and-nin-models-96e4bf398484


In [16]:


# 创建全一数组
ones_array = np.ones((3, 3))
print("全一数组：\n", ones_array)

# 创建指定范围的数组
range_array = np.arange(0, 10, 2)  # 从0到10，步长为2
print("指定范围的数组：", range_array)

# 创建等间隔的数组
linspace_array = np.linspace(0, 5, 10)  # 从0到5，生成10个等间隔的数
print("等间隔的数组：", linspace_array)

# 创建随机数组
random_array = np.random.rand(3, 3)  # 生成一个3x3的随机数组
print("随机数组：\n", random_array)


全一数组：
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
指定范围的数组： [0 2 4 6 8]
等间隔的数组： [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
随机数组：
 [[0.91787368 0.63114378 0.4946784 ]
 [0.7416772  0.5228661  0.60821969]
 [0.86481856 0.758726   0.31946533]]


In [18]:
ones_array*random_array

array([[0.91787368, 0.63114378, 0.4946784 ],
       [0.7416772 , 0.5228661 , 0.60821969],
       [0.86481856, 0.758726  , 0.31946533]])

In [19]:
random_array*random_array

array([[0.84249209, 0.39834247, 0.24470672],
       [0.55008508, 0.27338896, 0.36993119],
       [0.74791114, 0.57566514, 0.10205809]])

In [21]:
# 数组的形状
print("数组形状：", random_array.shape)

# 数组的大小
print("数组大小：", random_array.size)

# 数组的维度
print("数组维度：", random_array.ndim)

# 数组的数据类型
print("数组数据类型：", random_array.dtype)


数组形状： (3, 3)
数组大小： 9
数组维度： 2
数组数据类型： float64


In [22]:
# 访问数组元素
print("第一个元素：", arr_from_list[0])
print("最后一个元素：", arr_from_list[-1])
print("前三个元素：", arr_from_list[:3])
print("后两个元素：", arr_from_list[-2:])

# 数组的转置
arr_transposed = np.transpose(arr_from_list)
print("数组转置：", arr_transposed)

# 数组的重塑
reshaped_array = arr_from_list.reshape(5, 1)
print("重塑后的数组：\n", reshaped_array)

# 数组的拼接
concatenated_array = np.concatenate([arr_from_list, arr_from_list])
print("拼接后的数组：", concatenated_array)


第一个元素： 1
最后一个元素： 5
前三个元素： [1 2 3]
后两个元素： [4 5]
数组转置： [1 2 3 4 5]
重塑后的数组：
 [[1]
 [2]
 [3]
 [4]
 [5]]
拼接后的数组： [1 2 3 4 5 1 2 3 4 5]


In [23]:
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

# 数组相加
print("数组相加：\n", arr_a + arr_b)

# 数组相减
print("数组相减：\n", arr_a - arr_b)

# 数组相乘
print("数组相乘：\n", arr_a * arr_b)

# 数组相除
print("数组相除：\n", arr_a / arr_b)

# 数组平方根
print("数组平方根：\n", np.sqrt(arr_a))


数组相加：
 [[ 6  8]
 [10 12]]
数组相减：
 [[-4 -4]
 [-4 -4]]
数组相乘：
 [[ 5 12]
 [21 32]]
数组相除：
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
数组平方根：
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [25]:
arr_c = np.array([[1, 0], [3, 4]])

# 数组大于2的元素
print("数组大于2的元素：\n", arr_c > 2)

# 数组是否存在0元素
print("数组是否存在0元素：", np.any(arr_c == 0))


数组大于2的元素：
 [[False False]
 [ True  True]]
数组是否存在0元素： True


In [7]:
# 数组的最小值
print("数组的最小值：", np.min(arr_a))

# 数组的最大值
print("数组的最大值：", np.max(arr_a))

# 数组的平均值
print("数组的平均值：", np.mean(arr_a))

# 数组的标准差
print("数组的标准差：", np.std(arr_a))

# 数组的和
print("数组的和：", np.sum(arr_a))


数组的最小值： 1
数组的最大值： 4
数组的平均值： 2.5
数组的标准差： 1.118033988749895
数组的和： 10


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 访问数组元素
print("第一行第一列的元素：", arr[0, 0])

# 获取第二行
print("第二行：", arr[1, :])

# 获取第一列
print("第一列：", arr[:, 0])

# 切片
print("前两行：\n", arr[:2, :])


第一行第一列的元素： 1
第二行： [4 5 6]
第一列： [1 4 7]
前两行：
 [[1 2 3]
 [4 5 6]]


In [16]:
# 使用迭代遍历数组
for row in arr:
    print(row)


[1 2 3]
[4 5 6]
[7 8 9]


In [17]:
# 使用 flatten() 方法将多维数组转换为一维数组
flatten_arr = arr.flatten()
print("一维数组：", flatten_arr)


一维数组： [1 2 3 4 5 6 7 8 9]
